"""empty message

Revision ID: 1d86ffc94240
Revises: 5a008dae15a9
Create Date: 2023-07-22 12:39:36.853335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d86ffc94240'
down_revision = '5a008dae15a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
